name: TogglePvp
version: '${project.version}'
main: com.literallypurple.togglepvp.Main
api-version: 1.19
authors: [ LiterallyPurple ]
description: This plugin has a toggle command for pvp.
commands:
  pvpToggle:
    description: This toggles pvp on/off
    usage: /<command>
